# Generated by Django 5.2.10 on 2026-02-28 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companyworkday',
            unique_together={('filial', 'day')},
        ),
    ]
